name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

env:
  DEPLOY_PATH: /var/www/hebs-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "." # you can refine this to upload only necessary files
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1

      - name: Start/Restart Next.js app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            npm install --omit=dev
            pkill -f "next start" || true
            nohup npm run start &> nextjs.log &
