name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SCP Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Clean Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf /var/www/hebs-frontend/*

      - name: Upload Files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json,next.config.js,vercel.json"
          target: "/var/www/hebs-frontend"
          rm: true
          overwrite: true

      - name: Restart App with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/hebs-frontend
            npm install --omit=dev
            pm2 reload hebs-frontend || pm2 start npm --name hebs-frontend -- start
