name: Deploy Next.js Frontend to EC2

on:
  push:
    branches:
      - main # or change to your deploy branch

env:
  DEPLOY_PATH: /var/www/hebs-frontend 

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart with PM2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ${{ env.DEPLOY_PATH }}
            git pull origin main
            yarn install
            yarn build
            pm2 restart ecosystem.config.json || pm2 start ecosystem.config.json
          EOF
